---
# handlers file for roles/common
- name: Restart SSH
  service:
    name: ssh
    state: restarted

# handlers file for roles/common
- name: Restart Zabbix Agent
  ansible.builtin.systemd:
    name: zabbix-agent2
    state: restarted
